# This rule is not used by the project homelab-gateway-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over demo.hmdyt.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: homelab-gateway-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-admin-role
rules:
- apiGroups:
  - demo.hmdyt.github.io
  resources:
  - samples
  verbs:
  - '*'
- apiGroups:
  - demo.hmdyt.github.io
  resources:
  - samples/status
  verbs:
  - get
